version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: go-ad-postgres-db
    environment:
      POSTGRES_DB: goad
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "54321:5432"
    volumes:
      - ./internal/database:/docker-entrypoint-initdb.d:ro
